function [accelOpwn,gyroOpwn]=AddProcessNoise(accelOp,gyroOp,P)
accelOpwn=accelOp+[...
    randn(1)*P.sax;...
    randn(1)*P.say;...
    randn(1)*P.saz];
gyroOpwn=gyroOp+[...
    randn(1)*P.sp;...
    randn(1)*P.sq;...
    randn(1)*P.sr];

